apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-example
  labels:
    app: nginx-rs-pod
spec:
  # A deployment's specification really only has a few useful options
  # 1. How many copies of each pod do we want?
  replicas: 5  # replicatset
# 2. How do want to update the pods?
# strategy: Recreate
  
# 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      purpose: example-1
  
  # This template field is a regular pod configuration nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        purpose: example-1
        type: web
    spec:
      containers:
        - name: spring 
          image: malleshdevops/jenkins-flow-test:spring-v1
